dist: bionic
language: node_js
node_js:
  - '14'
services:
  - mongodb
  - redis-server
cache: yarn
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # check version
  - node --version
  - npm --version
  - yarn --version
  - mongo --version
  #copy default config testing
  - cp .env.test.example .env.test
script:
  - npm run build
  - npm run test:codecov
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report coverage/lcov.info
