dist: bionic
language: node_js
node_js:
  - '10'
services:
  - mongodb
  - redis-server
cache: npm
branches:
  only:
    - development
before_script:
  - echo -e "machine github.ibm.com\n  login $GIT_TOKEN" > ~/.netrc
  - npm install
  # check version
  - node --version
  - mongo --version

  #copy default config testing
  - cp env.test.example .env.test
script:
  - npm run test