language: node_js
node_js:
  - '10'
  - '12'
services:
  - mongodb
  - redis-server
cache: yarn
branches:
  only:
    - development
before_script:
  # check version
  - node --version
  - mongo --version

  #copy default config testing
  - cp env.test.example .env.test
script:
  - yarn
  - yarn test